# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: test-basic

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js using ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      - run: npm test
      - run: npm run coverage
